# Part I - Administrative {-}


# Introduction

Identifying and addressing the varied levels of preparedness of newly enrolled college students is one of the biggest issues facing higher education today. Currently, most institutions address this issue in two steps: (1) administer a required placement exam to incoming students (that assesses only reading, writing, and mathematics); and (2) place students into a remediation program if they do poorly on the placement exam. Unfortunately, this approach has been shown to be ineffective. Placement exams fail to accurately predict student success and remediation programs hinder progress toward a degree since the majority of students drop out of these noncredit courses that operate in isolation from the classroom, with no regard for program of study requirements. We propose to replace this faulty system with a formative assessment as means for students to assess their abilities and then develop personalized strategies, with guidance, to attain college-level skills.

## What is DAACS?

A <span title="“A range of formal and informal assessment procedures… undertaken by teachers in the classroom as an integral part of the normal teaching and learning process in order to modify and enhance learning and understanding.” --Crooks (2001)">formative assessment</span> and technology framework that assess and provide feedback on:

-Reading
-Writing
-Mathematics
-College Skills

“College Skills” is broad-based psychometric exam that will develop a picture of the student’s motivation, grit (stick-to-it and resilience), meta-cognition (thinking, planning, and assessment / reassessment of approaches to learning), etc. Each assessment (with the exception of the writing portion) will be comprised of a pool of test questions.

### Key Feature List

The DAACS Application framework provides post-secondary institutions with the automated ability to:

-deliver the four assessments to students, 
-collect and store the results of those assessment,
-refer the student to online resources that may improve their assessment scores and,
-provide access to the store data for academic counselors and researchers. 

The aforementioned combined functionality is what we refer to as the “DAACS Engine".

## Why is DAACS necessary?

College placement exams (e.g. Accuplacer, ACT Compass):
-Fail to predict college success (Bettinger, Evans, & Pope, 2011; Belfield & Crosta, 2012)
-Have issues related to reliability and validity (Mellard & Andreson, 2007)
-Don’t provide students with meaningful and/or actionable feedback
-Expensive


## Review of Literature supporting DAACS


## Implementation considerations. 
 

### Three levels of student interaction with DAACS.


### Role of advisors and mentors.
