# Part II - Technical Specifications {-}

Part two of this manual will describe the technical details about deploying DAACS.

## Hosting Environment
DAACS was designed to be easily deployed to a cloud-hosting environment. The author assumes the use of Amazon cloud services. However, the reader may safely choose any environment capable of operating the required version of the Linux operating system (e.g. other virtualization technology, physical platform, etc.).

## Application Architecture



## Installation

This manual assumes that the reader is familiar with Amazon Web Services EC2 and has an established AWS environment. For more information regarding getting started with AWS, please see <a href'"http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/get-set-up-for-amazon-ec2.html">Amazon AWS setup</a>

Generic Steps to install DAACS:

1. Create AWS EC2 instance
2. Select the proper Amazon Machine Image (AMI) and install the image
3. Java install
4. Docker install
5. System configuration
6. Install daacsweb and daacsapi Docker containers
7. What am I missing?
